# Generated by Django 5.0.6 on 2024-07-23 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='location',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
