# Generated by Django 5.0.6 on 2024-07-23 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_event_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='event',
            name='updated_at',
        ),
    ]
